services:
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "81:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    profiles:
      - dev
  
  app-prod:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    profiles:
      - prod

  user-db:
    container_name: user-db
    image: postgres:17.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: us-db
      POSTGRES_PASSWORD: 123
      